### ISSUE TITLE
How do we get the dock on multiple monitors

### ISSUE THREAD

**Issue by kasunsiyambalapitiya** [dikiaap/go-plank-theme#5]
Current it is supported only one display, either on Primary Display or on any of the selected display. I would be great if we can have the dock in all the connected displays

**Comment by dikiaap** [comment]
@kasunsiyambalapitiya I'm sorry for the very late reply. Have you fixed your display? Sorry I can't reproduce this issue due to me only using one monitor. I search the issue, and I believe this is on software side rather than on the theme side because people do tweaking their OS or installing an extra package so it can support multiple monitors. Search is your friend there as well.
